### PR TITLE
Manage course page #150

### PR DESCRIPTION
**Pull request by Shripad1020**
Manage Courses Page #150 
- Created Manage Courses Page to view all current courses and filter according to semester
- Ability to change professor or delete a particular course. 
- Dark theme Card view and css class for required (*) mark

### CODE REVIEW

**Comment by zacharylaguna** [comment]
lots of merge conflicts.

please do 

git checkout ManageCoursePage
git pull
git rebase origin/dev

and fix the merge conflicts

then 
git add --all
git rebase --continue

and repeat until done

**Comment by zacharylaguna** [comment]
Try to consult previous code changers as to which change is the right change

**Comment by zacharylaguna** [comment]
Never mind I rebased it for you

**Comment by hunterzacha** [comment]
looks good, write some rspec + cucumber tests and we can merge

**Comment by Shripad1020** [comment]
For manage course page both Rspec and Cucumber coverage is over 90%

**Pull request merged**
